FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
# ENV MUJOCO_GL=osmesa
# ENV PYOPENGL_PLATFORM=osmesa
ADD ./agent /
ADD ./utils /
ADD requirements/agent.txt /

RUN pip install --upgrade pip
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r agent.txt

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn\/debian-security/g' /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update
RUN apt install -y git
RUN apt install -y libgl1-mesa-glx libosmesa6

CMD [ "python", "agent_maniMPL.py" ]
